name: iteraio
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_local_notifications: ^1.4.4+1
  # Firebase
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  firebase_crashlytics: ^0.1.4+1
  firebase_messaging: ^7.0.0
  firebase_in_app_messaging: ^0.2.1
  # Flare
  flare_flutter: any
  # Essentials
  flutter_launcher_icons: ^0.7.2+1
  intl: ^0.16.1
  flutter_markdown: ^0.4.2
  fluttertoast: ^4.0.0
  html: null
  http: ^0.12.2
  splashscreen: null
  line_awesome_icons: ^1.0.4+2
  draggable_scrollbar: ^0.0.4
  flutter_slidable: ^0.5.7
  # forms
  flutter_form_builder: ^3.14.1
  flutter_chips_input: ^1.9.4
  # Alert Dialog / Update
  overlay_support: ^1.0.5
  package_info: ^0.4.3
  rflutter_alert: ^1.1.0
  shared_preferences: ^0.5.12+4
  # Path
  path_provider: ^1.6.22
  path: ^1.7.0
  # Url Handler
  url_launcher: ^5.6.0
  webview_flutter: ^1.0.6
  # Report bugs
  wiredash: ^0.1.0
  # Restart
  flutter_phoenix: "^0.1.0"
  # Share
  share_files_and_screenshot_widgets: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/icon.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/logos/
    - assets/animations/
    - assets/policy/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
