name: iteraio
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  wiredash: ^0.1.0

  package_info: ^0.4.3
  flare_flutter: any
  flutter_markdown: ^0.4.2

  http: ^0.12.0+2
  fluttertoast: ^4.0.0
  # video_player: ^0.10.11
  # chewie: ^0.9.10
  webview_flutter: ^0.3.21
  line_awesome_icons: ^1.0.4+2
  html: null
  url_launcher: null
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7+3
  splashscreen: null
  flutter_launcher_icons: ^0.7.2+1

  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_crashlytics: ^0.1.3+3
  # cloud_firestore: ^0.12.9+5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/icon.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/logos/
    - assets/animations/
    - assets/policy/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
